### ISSUE TITLE
`subscription.people` is undefined.

### ISSUE THREAD

**Issue by RealSGII2** [leggett/simplify#715]
I'd be happy to give any more details if needed.

#### Reproduction
1. Make a simpl.fyi account (trial has already expired by this time)
2. Sign up for a plan
3. Manage subscription
4. Blank page appears with the following error in the console:

#### Stacktrace
```
util.ts:556 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at we (Subscription.js:36:28)
    at sa (react-dom.production.min.js:157:137)
    at Gs (react-dom.production.min.js:267:460)
    at Nu (react-dom.production.min.js:250:347)
    at Ou (react-dom.production.min.js:250:278)
    at Tu (react-dom.production.min.js:250:138)
    at bu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
```

#### Problem Line
```js
const usedSeats = Object.keys(subscription.people).length;
```

---
System: Mozilla/5.0 (Windows NT 10.0

**Comment by leggett** [comment]
This happens when you sign up under an account that was already attached to another plan. Can you email me at hi@simpl.fyi and we can sort it out? Thanks!

**Comment by RealSGII2** [comment]
Thanks! I'll email you.
